version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: crazyuser
      POSTGRES_PASSWORD: crazypassword
      POSTGRES_DB: crazydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crazyreal.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # PGADMIN via http://localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: